/* tslint:disable */
/* eslint-disable */
/**
 * Todo example
 * The todo API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateTodoDto
 */
export interface CreateTodoDto {
    /**
     *
     * @type {string}
     * @memberof CreateTodoDto
     */
    task: string;
    /**
     *
     * @type {string}
     * @memberof CreateTodoDto
     */
    completedAt?: string | null;
}
