/* tslint:disable */
/* eslint-disable */
/**
 * Todo example
 * The todo API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Todo
 */
export interface Todo {
    /**
     *
     * @type {number}
     * @memberof Todo
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof Todo
     */
    task: string;
    /**
     *
     * @type {string}
     * @memberof Todo
     */
    completedAt: string | null;
    /**
     *
     * @type {string}
     * @memberof Todo
     */
    createdAt: string;
}
