/* tslint:disable */
/* eslint-disable */
/**
 * Todo example
 * The todo API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateTodoDto
 */
export interface UpdateTodoDto {
    /**
     *
     * @type {string}
     * @memberof UpdateTodoDto
     */
    task?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateTodoDto
     */
    completedAt?: string | null;
}
